
spring:
  datasource:
    url: jdbc:mysql:///cloud?serverTimezone=UTC&useUnicode=true&charecterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com  # 服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
