server:
  port: 8005
spring:
  application:
    name: cloud-providerconsul-payment
  datasource:
    url: jdbc:mysql:///cloud?serverTimezone=UTC&useUnicode=true&charecterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: 192.168.43.19
      port: 8500
      discovery:
        service-name: ${spring.application.name}
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
